### ISSUE TITLE
Is there any plan to store data in S3

### ISSUE THREAD

**Issue by jsvisa** [hydradatabase/hydra#43]
Currently, we are using GreenPlum as our Data Warehouse, but the performance is a little poor, so we are looking for some PostgreSQL's alternatives, we are looking at Hydra and TimescaleDB. Seems TimescaleDB will support 
 retention policy(move old data into s3 to save disk space) https://www.timescale.com/blog/save-money-and-improve-performance-by-carefully-managing-your-time-series-data/ .

So does Hydra has some similar plans to support it?

**Comment by wuputah** [comment]
It's not automated yet, but you can export data to S3 then access it via either S3 CSV or S3 Parquet External Tables. The absolutely cleanest way of doing this would be to partition tables you anticipate being archived later, e.g. [make monthly or quarterly partitions](https://docs.hydra.so/concepts/using-hydra-columnar#partitioning), then you can export (then drop) these tables in their entirety. Alternately you could export time ranges to CSV and then DELETE this data from your tables.

In short:

1) [Export data](https://stackoverflow.com/questions/29190632/how-to-export-a-postgresql-query-output-to-a-csv-file) - you'll need to use the psql `\copy` command rather than the `COPY` SQL query, unless using Hydra open source and you have access to the local filesystem of the server.
2) Optional but recommended for large files, [convert it to parquet](https://stackoverflow.com/questions/50604133/convert-csv-to-parquet-file-using-python)
3) Upload to S3
4) [Set up access to this data from Hydra](https://docs.hydra.so/concepts/using-hydra-external-tables), if desired
5) Delete the data from your database

We do plan on expanding this feature in the future, e.g. automation of this process or other ways to archive / store your data in S3.
